name: 'PHP Lint'
description: 'Run Lint Against Pull Request'
author: 'Michael Wright <php-lint@wserver.co.uk>'
inputs:
  dir:
    description: 'Folder to check syntax'
    required: false
    default: '.'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.dir }}
branding:
  icon: 'eye'  
  color: 'gray-dark'
